# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true

# Plugins
modmuss50_mod_publish_version        = 2.1.1
fabric_loom_version                  = 1.17-SNAPSHOT
neoform_version                      = 26.3-1

# Project
modrinthID				             = tbd
curseforgeID			             = tbd
projectSlug				             = tbd

# Common
java_version                         = 25
minecraft_version                    = 26.3

# NeoForge
loader_version_range                 = [4,)
minecraft_version_range              = [26.3, 26.4)
neo_moddev                           = 2.0.147
neo_version                          = 26.3.0.48-beta
neo_version_range                    = [26.3,)

# Fabric
fabric_version                       = 0.160.5+26.3
fabric_loader_version                = 0.19.5

# Libs
modmenu_version                      = 21.0.0
azurelib_version                     = 4.0.8

# Mod options
group                                = mod.azure.renameme
mod_name                             = Rename Me
mod_author                           = renameme
mod_id                               = renameme
mod_license                          = renameme
mod_description                      = renameme
mod_credits                          = renameme
mod_logo                             = icon.png
mod_url                              = renameme
mod_issues                           = renameme
mod_sources                          = renameme
version                              = 1.0.0
