plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

neoForge {
    version = "${neo_version}"
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "mod.azure.azurelib:azurelib-neo-${minecraft_version}:${azurelib_version}"
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        file = jar.archiveFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("neoforge")

        curseforge {
            projectId = project.curseforgeID
            projectSlug = project.projectSlug
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
        }
        modrinth {
            projectId = project.modrinthID
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
        }
    }
}
